# Generated by Django 4.0.5 on 2022-06-23 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('csuid', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=14)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_register.course')),
            ],
        ),
    ]
